import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material';
import { Montserrat } from 'next/font/google';
import { Darumadrop_One } from 'next/font/google';

const darumadrop = Darumadrop_One({
  weight: '400', // Only available in 400 weight
  subsets: ['latin'],
  display: 'swap',
});


const montserrat = Montserrat({
  weight: ['400', '700'], // Choose the weights you need
  subsets: ['latin'],
  display: 'swap',
});

import theme from '../theme';
import "./globals.css";

export const metadata: Metadata = {
  title: "erina dot dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <AppRouterCacheProvider>
          <body className={montserrat.className}>
            {children}
          </body>
        </AppRouterCacheProvider>
      </ThemeProvider>
    </html>
  );
}
